#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=u8510
MANUFACTURER=huawei

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/wifi
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/bluetooth
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/firmware
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/egl
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi


adb pull system/etc/vold.fstab ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/vold.fstab
adb pull system/etc/init.qcom.bt.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/init.qcom.bt.sh
adb pull system/etc/apns-conf.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/apns-conf.xml
adb pull system/etc/media_profiles.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/media_profiles.xml
adb pull system/etc/wifi/wpa_supplicant.conf ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/wifi/wpa_supplicant.conf
adb pull system/etc/AudioFilter.csv ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/AudioFilter.csv
adb pull system/etc/firmware/yamato_pfp.fw ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/firmware/yamato_pfp.fw
adb pull system/etc/firmware/yamato_pm4.fw ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/firmware/yamato_pm4.fw
adb pull system/etc/init.qcom.coex.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/init.qcom.coex.sh
adb pull system/etc/init.qcom.fm.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/init.qcom.fm.sh
adb pull system/etc/init.qcom.post_boot.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/init.qcom.post_boot.sh
adb pull system/etc/init.qcom.sdio.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/init.qcom.sdio.sh
adb pull system/etc/bluetooth/BCM4329.hcd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/bluetooth/BCM4329.hcd

adb pull system/wifi/firmware.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/firmware.bin
adb pull system/wifi/firmware_apsta.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/firmware_apsta.bin
adb pull system/wifi/nvram.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/nvram.txt
adb pull system/wifi/bcm_loadecho.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/bcm_loadecho.sh
adb pull system/wifi/bcm_loadipf.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/bcm_loadipf.sh
adb pull system/wifi/connectap.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/connectap.sh
adb pull system/wifi/iwconfig ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/iwconfig
adb pull system/wifi/iwlist ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/iwlist
adb pull system/wifi/iwpriv ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/iwpriv
adb pull system/wifi/nvram.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/nvram.txt
adb pull system/wifi/udp_server ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wifi/udp_server

adb pull system/lib/libril-qc-1.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libril-qc-1.so
adb pull system/lib/libril-qcril-hook-oem.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libril-qcril-hook-oem.so
adb pull system/lib/libgsl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libgsl.so
adb pull system/lib/libdiag.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libdiag.so
adb pull system/lib/libcm.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libcm.so
adb pull system/lib/liboncrpc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/liboncrpc.so
adb pull system/lib/libqmi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libqmi.so
adb pull system/lib/libdsm.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libdsm.so
adb pull system/lib/libqueue.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libqueue.so
adb pull system/lib/libdll.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libdll.so
adb pull system/lib/libmmgsdilib.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libmmgsdilib.so
adb pull system/lib/libgsdi_exp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libgsdi_exp.so
adb pull system/lib/libgstk_exp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libgstk_exp.so
adb pull system/lib/libwms.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libwms.so
adb pull system/lib/libnv.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libnv.so
adb pull system/lib/libwmsts.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libwmsts.so
adb pull system/lib/libpbmlib.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libpbmlib.so
adb pull system/lib/libdss.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libdss.so
adb pull system/lib/libauth.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libauth.so
adb pull system/lib/libcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libcamera.so
adb pull system/lib/liboemcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/liboemcamera.so
adb pull system/lib/libcameraservice.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libcameraservice.so
adb pull system/lib/libcamera_client.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libcamera_client.so
adb pull system/lib/libmmjpeg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libmmjpeg.so
adb pull system/lib/libmmipl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libmmipl.so
adb pull system/lib/libmm-adspsvc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libmm-adspsvc.so
adb pull system/lib/libOmxAacDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAacDec.so
adb pull system/lib/libOmxWmvDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxWmvDec.so
adb pull system/lib/libOmxAdpcmDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAdpcmDec.so
adb pull system/lib/libOmxH264Dec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxH264Dec.so
adb pull system/lib/libOmxAmrDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAmrDec.so
adb pull system/lib/libOmxAmrwbDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAmrwbDec.so
adb pull system/lib/libOmxWmaDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxWmaDec.so
adb pull system/lib/libOmxMp3Dec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxMp3Dec.so
adb pull system/lib/libOmxMpeg4Dec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxMpeg4Dec.so
adb pull system/lib/libOmxAmrRtpDec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAmrRtpDec.so
adb pull system/lib/libOmxAacEnc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAacEnc.so
adb pull system/lib/libOmxEvrcEnc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxEvrcEnc.so
adb pull system/lib/libOmxAmrEnc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxAmrEnc.so
adb pull system/lib/libOmxQcelp13Enc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxQcelp13Enc.so
adb pull system/lib/libOmxVidEnc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libOmxVidEnc.so
adb pull system/lib/libomx_aacdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_aacdec_sharedlibrary.so
adb pull system/lib/libomx_amrdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_amrdec_sharedlibrary.so
adb pull system/lib/libomx_amrenc_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_amrenc_sharedlibrary.so
adb pull system/lib/libomx_avcdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_avcdec_sharedlibrary.so
adb pull system/lib/libomx_m4vdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_m4vdec_sharedlibrary.so
adb pull system/lib/libomx_mp3dec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_mp3dec_sharedlibrary.so
adb pull system/lib/libomx_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libomx_sharedlibrary.so
adb pull system/lib/libreference-ril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libreference-ril.so
adb pull system/lib/libril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libril.so
adb pull system/lib/liboem_rapi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/liboem_rapi.so
adb pull system/lib/libcommondefs.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libcommondefs.so
adb pull system/lib/libloc_api-rpc-qc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libloc_api-rpc-qc.so
adb pull system/lib/libmmprocess.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libmmprocess.so
adb pull system/lib/libhwrpc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/libhwrpc.so

adb pull system/bin/oem_rpc_svc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/oem_rpc_svc
adb pull system/bin/vold ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/vold
adb pull system/bin/modempre ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/modempre
adb pull system/bin/wpa_supplicant ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/wpa_supplicant
adb pull system/bin/wl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/wl
adb pull system/bin/port-bridge ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/port-bridge
adb pull system/bin/brcm_patchram_plus ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/brcm_patchram_plus
adb pull system/bin/qmuxd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/qmuxd
adb pull system/bin/akmd8962 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/akmd8962
adb pull system/bin/akmd8975 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/akmd8975
adb pull system/bin/compassd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/compassd

adb pull system/lib/hw/sensors.default.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw/sensors.default.so
adb pull system/lib/hw/lights.msm7k.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw/lights.msm7k.so
adb pull system/lib/hw/copybit.msm7k.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw/copybit.msm7k.so
adb pull system/lib/hw/gralloc.msm7k.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw/gralloc.msm7k.so
adb pull system/lib/hw/gps.default.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/hw/gps.default.so

adb pull system/lib/egl/libEGL_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/egl/libEGL_adreno200.so
adb pull system/lib/egl/libGLESv2_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/egl/libGLESv2_adreno200.so
adb pull system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/egl/libGLESv1_CM_adreno200.so
adb pull system/lib/egl/libq3dtools_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib/egl/libq3dtools_adreno200.so

chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bin/* 

./setup-makefiles.sh
